# ═══════════════════════════════════════════════════════════
#  N-THEME — Ayu Dark Theme
#  Author: Mohammad Noyon Mahmud
# ═══════════════════════════════════════════════════════════

background   = #0A0E14
foreground   = #B3B1AD
cursor       = #E6B450

color0   = #01060E
color8   = #32394D

color1   = #EA6C73
color9   = #F07178

color2   = #91B362
color10  = #C2D94C

color3   = #F9AF4F
color11  = #FFB454

color4   = #53BDFA
color12  = #59C2FF

color5   = #FAE994
color13  = #FFEE99

color4   = #53BDFA
color9   = #F07178

color6   = #90E1C6
color14  = #95E6CB

color7   = #C7C7C7
color15  = #FFFFFF
