# ═══════════════════════════════════════════════════════════
#  N-THEME — Cobalt2 Theme
#  Author: Mohammad Noyon Mahmud
# ═══════════════════════════════════════════════════════════

background   = #193549
foreground   = #FFFFFF
cursor       = #FFC600

color0   = #000000
color8   = #555555

color1   = #FF0000
color9   = #FF628C

color2   = #38DE21
color10  = #3AD900

color3   = #FFE50A
color11  = #FFC600

color4   = #1460D2
color12  = #0088FF

color5   = #FF005D
color13  = #FB94FF

color6   = #00BBBB
color14  = #80FCFF

color7   = #BBBBBB
color15  = #FFFFFF
