# ═══════════════════════════════════════════════════════════
#  N-THEME — Termux Properties
#  Author: Mohammad Noyon Mahmud
# ═══════════════════════════════════════════════════════════

# Extra keys
extra-keys = [['ESC','TAB','CTRL','ALT','LEFT','DOWN','UP','RIGHT'],['/','ls','$','~','-','|','ENTER','BKSP']]

# Cursor
terminal-cursor-style = underline
terminal-cursor-blink-rate = 600

# Bell
bell-character = vibrate

# Fullscreen
fullscreen = false

# Back key
back-key = escape

# Terminal margin
terminal-margin-horizontal = 0
terminal-margin-vertical = 0

# Allow external apps
allow-external-apps = true
